### PR TITLE
status: Expose datetime of most recent block

### PR DESCRIPTION
**Pull request by ptrus**
Resloves https://app.clickup.com/t/866af85d2

Testing (locally):
```
curl "localhost:8008/v1/"
{"latest_block":8049056,"latest_block_time":"2022-04-11T13:12:48+02:00","latest_update":"2023-06-25T09:20:13+02:00"}


curl "localhost:8008/v1/emerald/status"
{"active_nodes":0,"latest_block":1004425,"latest_block_time":"2022-04-11T17:04:34+02:00","latest_update":"2023-06-25T09:18:49+02:00"}
```

### CODE REVIEW

**Review by aefhm — APPROVED** [review]
Happy weekend LGTM, but defer to the other gents.

**Review by pro-wh — APPROVED** [review]
lg here too

**Review by mitjat — APPROVED** [review]
Thank you, LGTM also!
Bummer that we "have to" make a separate query (instead of using a JOIN) because of the consensus/runtime distinction.

**Comment by mitjat** [comment]
Since the change is pretty small and there are no reviewer suggestions, I'll go against convention and merge this PR in. This way, it can make it into the release I'm hoping to cut in the next few hours.

**Pull request merged**
