### PR TITLE
Revert "Strenghten sql constraints"

### PR DESCRIPTION
**Pull request by mitjat**
Reverts oasisprotocol/oasis-indexer#217

I merged that PR unintentionally vie the auto-merge feature, despite failing e2e tests.

### CODE REVIEW

**Comment by pro-wh** [comment]
will it need a more extensive fix?

we can merge this revert if we need to make a release or something :shrug:

**Comment by pro-wh** [comment]
oh I see there are PRs open to add more logging to help diagnose.

we can revert if you want. fyi auto-merge is enabled on this PR too. so let's approve when we're ready to go ahead with this

**Comment by mitjat** [comment]
I figure it's annoying for anyone who wants to work on top of `main`. But if nobody's in a rush, I can fix forward yeah. I don't fully know the problem yet though. By now I know it's a bad cast somewhere (from go to sql). It's probably a one-line fix.

**Review by pro-wh — APPROVED** [review]
gonna leave this on approved in case we want it

no actual code review, I'll just take your word for it that this is a correct revert

**Comment by mitjat** [comment]
Thanks. We don't need the PR after all; forward-fixed in https://github.com/oasisprotocol/oasis-indexer/pull/221

**Pull request closed without merging**
