### PR TITLE
Emerald: store some fields as bytea

### LINKED ISSUE #165: Emerald: bytea for some fields
https://github.com/oasisprotocol/oasis-indexer/pull/147#discussion_r991802720

### PR DESCRIPTION
**Pull request by pro-wh**
fixes #165

### CODE REVIEW

**Review by mitjat — APPROVED** [review]
Thank you, LGTM assuming tests pass.

**Comment by pro-wh** [comment]
converting back to draft tho, there's a weird inconsistency with the address preimage data being hex text

**Comment by pro-wh** [comment]
rationales for hex text apply to both:

- text is human readable https://github.com/oasisprotocol/oasis-indexer/pull/147#discussion_r990571032

rationales for bytea apply to both:

- more compact https://github.com/oasisprotocol/oasis-indexer/pull/147#discussion_r991802720
- less processing
- better documents the nature of the data

consistency too tho, that's something that would be good to preserve

**Comment by pro-wh** [comment]
discussed on slack, we are in agreement about address_data being bytea as well

**Comment by mitjat** [comment]
:+1: when I pushed for the address to be `TEXT`, that was based on poor understanding of how addresses are generated and what `address_data` is.

I wanted to add: if it's ever useful to have `address_data` formatted a certain way, we can add [generated columns](https://www.postgresql.org/docs/current/ddl-generated-columns.html), e.g. `address_data_as_eth_addr`, `address_data_as_ed25519_pubkey` (each serialized in their typical fashion).

**Pull request merged**
